"""Utilities for data preparation.
"""

import numpy as np

SCENE_NAMES = [
    "2013_05_28_drive_0000_sync",
    "2013_05_28_drive_0002_sync",
    "2013_05_28_drive_0003_sync",
    "2013_05_28_drive_0004_sync",
    "2013_05_28_drive_0005_sync",
    "2013_05_28_drive_0006_sync",
    "2013_05_28_drive_0007_sync",
    "2013_05_28_drive_0009_sync",
    "2013_05_28_drive_0010_sync",
]
SCENE_NAMES_TRAIN = [
    "2013_05_28_drive_0000_sync",
    "2013_05_28_drive_0002_sync",
    "2013_05_28_drive_0004_sync",
    "2013_05_28_drive_0006_sync",
    "2013_05_28_drive_0007_sync",
]
SCENE_NAMES_VAL = [
    "2013_05_28_drive_0010_sync",
]
SCENE_NAMES_TEST = [
    "2013_05_28_drive_0003_sync",
    "2013_05_28_drive_0005_sync",
    "2013_05_28_drive_0009_sync",
]

assert len(SCENE_NAMES_TRAIN + SCENE_NAMES_VAL + SCENE_NAMES_TEST) == 9
assert len(np.unique(SCENE_NAMES_TRAIN + SCENE_NAMES_VAL + SCENE_NAMES_TEST)) == 9

SCENE_SIZES = {
    "2013_05_28_drive_0000_sync": [735, 1061, 30],
    "2013_05_28_drive_0002_sync": [952, 1313, 89],
    "2013_05_28_drive_0003_sync": [713, 922, 34],
    "2013_05_28_drive_0004_sync": [1302, 2003, 60],
    "2013_05_28_drive_0005_sync": [801, 999, 51],
    "2013_05_28_drive_0006_sync": [881, 1004, 80],
    "2013_05_28_drive_0007_sync": [3049, 1989, 52],
    "2013_05_28_drive_0009_sync": [615, 1113, 26],
    "2013_05_28_drive_0010_sync": [1560, 1445, 29],
}

KNOWN_CLASS = ['box', 
                'bridge', 
                'building', 
                'fence', 
                'garage', 
                'guard rail', 
                'lamp', 
                'pad', 
                'parking', 
                'pole', 
                'road', 
                'sidewalk', 
                'smallpole', 
                'stop', 
                'terrain', 
                'traffic light', 
                'traffic sign', 
                'trash bin', 
                'tunnel', 
                'vegetation', 
                'vending machine', 
                'wall']

CLASS_TO_INDEX = {
    "building": 0,
    "pole": 1,
    "traffic light": 2,
    "traffic sign": 3,
    "garage": 4,
    "stop": 5,
    "smallpole": 6,
    "lamp": 7,
    "trash bin": 8,
    "vending machine": 9,
    "box": 10,
    "road": 11,
    "sidewalk": 12,
    "parking": 13,
    "wall": 14,
    "fence": 15,
    "guard rail": 16,
    "bridge": 17,
    "tunnel": 18,
    "vegetation": 19,
    "terrain": 20,
    "pad": 21,
}

CLASS_TO_LABEL = {
    "building": 11,
    "pole": 17,
    "traffic light": 19,
    "traffic sign": 20,
    "garage": 34,
    "stop": 36,
    "smallpole": 37,
    "lamp": 38,
    "trash bin": 39,
    "vending machine": 40,
    "box": 41,
    "road": 7,
    "sidewalk": 8,
    "parking": 9,
    "wall": 12,
    "fence": 13,
    "guard rail": 14,
    "bridge": 15,
    "tunnel": 16,
    "vegetation": 21,
    "terrain": 22,
}

CLASS_TO_COLOR = {
    "building": (70, 70, 70),
    "pole": (153, 153, 153),
    "traffic light": (250, 170, 30),
    "traffic sign": (220, 220, 0),
    "garage": (64, 128, 128),
    "stop": (150, 120, 90),
    "smallpole": (153, 153, 153),
    "lamp": (0, 64, 64),
    "trash bin": (0, 128, 192),
    "vending machine": (128, 64, 0),
    "box": (64, 64, 128),
    "sidewalk": (244, 35, 232),
    "road": (128, 64, 128),
    "parking": (250, 170, 160),
    "wall": (102, 102, 156),
    "fence": (190, 153, 153),
    "guard rail": (180, 165, 180),
    "bridge": (150, 100, 100),
    "tunnel": (150, 120, 90),
    "vegetation": (107, 142, 35),
    "terrain": (152, 251, 152),
    "_pose": (255, 255, 255),
}

CLASS_TO_MINPOINTS = {
    "building": 250,
    "pole": 25,
    "traffic light": 25,
    "traffic sign": 25,
    "garage": 250,
    "stop": 25,
    "smallpole": 25,
    "lamp": 25,
    "trash bin": 25,
    "vending machine": 25,
    "box": 25,
    "sidewalk": 1000,
    "road": 1000,
    "parking": 1000,
    "wall": 250,
    "fence": 250,
    "guard rail": 250,
    "bridge": 1000,
    "tunnel": 1000,
    "vegetation": 250,
    "terrain": 250,
    "_pose": 25,
}

CLASS_TO_VOXELSIZE = {
    "building": 0.25,
    "pole": None,
    "traffic light": None,
    "traffic sign": None,
    "garage": 0.125,
    "stop": None,
    "smallpole": None,
    "lamp": None,
    "trash bin": None,
    "vending machine": None,
    "box": None,
    "sidewalk": 0.25,
    "road": 0.25,
    "parking": 0.25,
    "wall": 0.125,
    "fence": 0.125,
    "guard rail": 0.125,
    "bridge": 0.25,
    "tunnel": 0.25,
    "vegetation": 0.25,
    "terrain": 0.25,
    "_pose": None,
}

STUFF_CLASSES = [
    "sidewalk",
    "road",
    "parking",
    "wall",
    "fence",
    "guard rail",
    "bridge",
    "tunnel",
    "vegetation",
    "terrain",
]

LABEL_TO_CLASS = {v: k for k, v in CLASS_TO_LABEL.items()}

COLORS = (
    np.array(
        [
            [47.2579917, 49.75368454, 42.4153065],
            [136.32696657, 136.95241796, 126.02741229],
            [87.49822126, 91.69058836, 80.14558512],
            [213.91030679, 216.25033052, 207.24611073],
            [110.39218852, 112.91977458, 103.68638249],
            [27.47505158, 28.43996795, 25.16840296],
            [66.65951839, 70.22342483, 60.20395996],
            [171.00852191, 170.05737735, 155.00130334],
        ]
    )
    / 255.0
)

# COLOR_NAMES = ['color-0', 'color-1', 'color-2', 'color-3', 'color-4', 'color-5', 'color-6', 'color-7']
"""
Note that these names are not completely precise as the fitted colors are mostly gray-scale.
However, the models just learn them as words without deeper meaning, so they don't have a more complex effect.
"""
COLOR_NAMES = ["dark-green", "gray", "gray-green", "bright-gray", "gray", "black", "green", "beige"]

from scipy.spatial.distance import cdist

dists = cdist(COLORS, COLORS)

sentence_style_t = [
    # "The pose is on top of {object}.",
    # "The pose is on-top of {object}.",
    "The pose is over {object}.",
    "The pose is above {object}.",
    "The pose lies over {object}.",
    "The pose lies above {object}.",
    "The pose is positioned directly above {object}.",
    "The pose is positioned directly over {object}.",
    "The pose is resting atop {object}.",
    "The pose is situated right over {object}.",
    "The pose is situated right above {object}.",
    "The pose is perched on top of {object}.",
    "The pose is firmly placed on top of {object}.",
    "The pose is positioned vertically over {object}.",
    "The pose is firmly resting on top of {object}.",
    "The pose is placed right over {object}.",
    "The pose is placed right above {object}.",
    "{Object} is the ground on which the pose is placed.",
    "{Object} serves as the surface beneath the pose.",
    "{Object} serves as the base for the pose."
    "{Object} acts as the foundation for the pose.",
    "{Object} serves as the surface beneath the pose.",
    "{Object} is the ground on which the pose is placed.",
]

sentence_style_n = [
    "The pose is located to the north of {object}.",
    "{Object} is positioned south of the pose." ,
    "When facing south at the pose, we can find {object}.",
    # "When facing north at {object}, we can find the pose.",
    "The pose lies at the northern side relative to {object}.",
    "{Object} is situated in the southern direction compared to the pose.",
    "The pose can be reached by traveling north from {object}.",
    # "Geographically, the pose is elevated to the north of {object}.".
    "The north side of the map corresponds to the pose's location, while {object} is in the south.",
    "{Object} is in the southern region relative to the pose.",
    "In terms of orientation, the pose faces north from {object}.",
    "To the upper side of {object} on a map, you'll discover the pose.",
    "{Object}'s placement is southward from the pose.",
    "The pose's placement is higher on the map, north of {object}.",
    "The spatial arrangement is such that the pose is positioned to the north compared to {object}.",
    "The pose is found northward from {object}.",
    "Traveling north from {object} leads you to the pose.", 
    "The pose is in the direction of the north with respect to {object}.",
    "In terms of cardinal directions, the pose is to the north of {object}.",
    "If you head south from the pose, you'll see {object}.",
    "If you head north from {object}, you'll see the pose.",
    "{Object} is located in the southern direction from the pose.",
    "On a map, the pose is northward from the location of {object}.",
    "In relation to {object}, the pose is positioned in the north.",
    "In relation to the pose, {object} is positioned in the south.",
    "The pose is positioned to the top of {object} on a geographic scale.",
    "North of {object} lies the pose.",
    "South of the pose lies {object}.",
    "{Object}'s location is to the south of the pose.",
    "The pose is the northern neighbor of {object}.",
    "The pose is geographically positioned higher than {object}.",
    "{Object} is situated in the southern part in comparison to the pose.",
    "In terms of directions, the pose is in the north of {object}.",
    "The pose can be located by moving north from {object}.",
    "In the northern direction lies the pose, relative to {object}.",
    "{Object} is positioned southward from the pose.",
    "The pose's placement is higher on the map, north of {object}.",
    "When facing southward at the pose, you encounter {object}.",
    "{Object} is situated in the southern region compared to the pose.",
    "In the context of directions, the pose is in the north relative to {object}.",
    "The pose can be reached by heading north from {object}'s position.",
    "The pose's geographic coordinates are oriented to the north of {object}.",
    "To the north of {object}, you'll find the pose.",
    "The map's upper part corresponds to the pose's position, while {object} is in the lower part.",
    "{Object} is situated to the south of the pose's point of reference.",
]

sentence_style_s = [
    "The pose is located to the south of {object}.",
    "{Object} is positioned north of the pose." ,
    "When facing north at the pose, we can find {object}.",
    # "When facing south at {object}, we can find the pose.",
    "The pose lies at the southern side relative to {object}.",
    "{Object} is situated in the northern direction compared to the pose.",
    "The pose can be reached by traveling south from {object}.",
    # "Geographically, the pose is elevated to the south of {object}.".
    "The south side of the map corresponds to the pose's location, while {object} is in the north.",
    "{Object} is in the northern region relative to the pose.",
    "In terms of orientation, the pose faces south from {object}.",
    "To the lower side of {object} on a map, you'll discover the pose.",
    "{Object}'s placement is northward from the pose.",
    "The pose's placement is lower on the map, south of {object}.",
    "The spatial arrangement is such that the pose is positioned to the south compared to {object}.",
    "The pose is found southward from {object}.",
    "Traveling south from {object} leads you to the pose.", 
    "The pose is in the direction of the south with respect to {object}.",
    "In terms of cardinal directions, the pose is to the south of {object}.",
    "If you head north from the pose, you'll see {object}.",
    "If you head south from {object}, you'll see the pose.",
    "{Object} is located in the northern direction from the pose.",
    "On a map, the pose is southward from the location of {object}.",
    "In relation to {object}, the pose is positioned in the south.",
    "In relation to the pose, {object} is positioned in the north.",
    "The pose is positioned to the bottom of {object} on a geographic scale.",
    "South of {object} lies the pose.",
    "North of the pose lies {object}.",
    "{Object}'s location is to the north of the pose.",
    "The pose is the southern neighbor of {object}.",
    "The pose is geographically positioned lower than {object}.",
    "{Object} is situated in the northern part in comparison to the pose.",
    "In terms of directions, the pose is in the south of {object}.",
    "The pose can be located by moving south from {object}.",
    "In the southern direction lies the pose, relative to {object}.",
    "{Object} is positioned northward from the pose.",
    "The pose's placement is higher on the map, south of {object}.",
    "When facing northward at the pose, you encounter {object}.",
    "{Object} is situated in the northern region compared to the pose.",
    "In the context of directions, the pose is in the south relative to {object}.",
    "The pose can be reached by heading south from {object}'s position.",
    "The pose's geographic coordinates are oriented to the south of {object}.",
    "To the south of {object}, you'll find the pose.",
    "The map's upper part corresponds to the pose's position, while {object} is in the lower part.",
    "{Object} is situated to the north of the pose's point of reference.",
]

sentence_style_e = [
    "The pose is located to the east of {object}.",
    "{Object} is positioned west of the pose." ,
    "When facing west at the pose, we can find {object}.",
    # "When facing east at {object}, we can find the pose.",
    "The pose lies at the eastern side relative to {object}.",
    "{Object} is situated in the western direction compared to the pose.",
    "The pose can be reached by traveling east from {object}.",
    # "Geographically, the pose is elevated to the east of {object}.".
    "The east side of the map corresponds to the pose's location, while {object} is in the west.",
    "{Object} is in the western region relative to the pose.",
    "In terms of orientation, the pose faces east from {object}.",
    "To the right side of {object} on a map, you'll discover the pose.",
    "{Object}'s placement is westward from the pose.",
    "The pose's placement is further right on the map, east of {object}.",
    "The spatial arrangement is such that the pose is positioned to the east compared to {object}.",
    "The pose is found eastward from {object}.",
    "Traveling east from {object} leads you to the pose.", 
    "The pose is in the direction of the east with respect to {object}.",
    "In terms of cardinal directions, the pose is to the east of {object}.",
    "If you head west from the pose, you'll see {object}.",
    "If you head east from {object}, you'll see the pose.",
    "{Object} is located in the western direction from the pose.",
    "On a map, the pose is eastward from the location of {object}.",
    "In relation to {object}, the pose is positioned in the east.",
    "In relation to the pose, {object} is positioned in the west.",
    "The pose is positioned to the right of {object} on a geographic scale.",
    "East of {object} lies the pose.",
    "West of the pose lies {object}.",
    "{Object}'s location is to the west of the pose.",
    "The pose is the eastern neighbor of {object}.",
    "The pose is geographically positioned further right than {object}.",
    "{Object} is situated in the western part in comparison to the pose.",
    "In terms of directions, the pose is in the east of {object}.",
    "The pose can be located by moving east from {object}.",
    "In the eastern direction lies the pose, relative to {object}.",
    "{Object} is positioned westward from the pose.",
    "The pose's placement is higher on the map, east of {object}.",
    "When facing westward at the pose, you encounter {object}.",
    "{Object} is situated in the western region compared to the pose.",
    "In the context of directions, the pose is in the east relative to {object}.",
    "The pose can be reached by heading east from {object}'s position.",
    "The pose's geographic coordinates are oriented to the east of {object}.",
    "To the east of {object}, you'll find the pose.",
    "The map's upper part corresponds to the pose's position, while {object} is in the lower part.",
    "{Object} is situated to the west of the pose's point of reference.",
]

sentence_style_w = [
    "The pose is located to the west of {object}.",
    "{Object} is positioned east of the pose." ,
    "When facing east at the pose, we can find {object}.",
    # "When facing west at {object}, we can find the pose.",
    "The pose lies at the western side relative to {object}.",
    "{Object} is situated in the eastern direction compared to the pose.",
    "The pose can be reached by traveling west from {object}.",
    # "Geographically, the pose is elevated to the west of {object}.".
    "The west side of the map corresponds to the pose's location, while {object} is in the east.",
    "{Object} is in the eastern region relative to the pose.",
    "In terms of orientation, the pose faces west from {object}.",
    "To the further left side of {object} on a map, you'll discover the pose.",
    "{Object}'s placement is eastward from the pose.",
    "The pose's placement is further left on the map, west of {object}.",
    "The spatial arrangement is such that the pose is positioned to the west compared to {object}.",
    "The pose is found westward from {object}.",
    "Traveling west from {object} leads you to the pose.", 
    "The pose is in the direction of the west with respect to {object}.",
    "In terms of cardinal directions, the pose is to the west of {object}.",
    "If you head east from the pose, you'll see {object}.",
    "If you head west from {object}, you'll see the pose.",
    "{Object} is located in the eastern direction from the pose.",
    "On a map, the pose is westward from the location of {object}.",
    "In relation to {object}, the pose is positioned in the west.",
    "In relation to the pose, {object} is positioned in the east.",
    "The pose is positioned to the left of {object} on a geographic scale.",
    "West of {object} lies the pose.",
    "East of the pose lies {object}.",
    "{Object}'s location is to the east of the pose.",
    "The pose is the western neighbor of {object}.",
    "The pose is geographically positioned further left than {object}.",
    "{Object} is situated in the eastern part in comparison to the pose.",
    "In terms of directions, the pose is in the west of {object}.",
    "The pose can be located by moving west from {object}.",
    "In the western direction lies the pose, relative to {object}.",
    "{Object} is positioned eastward from the pose.",
    "The pose's placement is higher on the map, west of {object}.",
    "When facing eastward at the pose, you encounter {object}.",
    "{Object} is situated in the eastern region compared to the pose.",
    "In the context of directions, the pose is in the west relative to {object}.",
    "The pose can be reached by heading west from {object}'s position.",
    "The pose's geographic coordinates are oriented to the west of {object}.",
    "To the west of {object}, you'll find the pose.",
    "The map's upper part corresponds to the pose's position, while {object} is in the lower part.",
    "{Object} is situated to the east of the pose's point of reference.",
]